apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reviews
  namespace: argocd
spec:
  project: default
  source:
    path: reviews
    repoURL: https://github.com/Jefferson-Butler1/summit2025-w04
    directory:
      include: "*.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: apollo-operator
  syncPolicy:
    automated: {}
